### ISSUE TITLE
最新(Flutter 2.10.5)環境でerrorが出て止まってしまう

### ISSUE THREAD

**Issue by shachi** [ymgn9314/import_path_converter#1]
**Describe the bug**
Flutter 2.10.5 / Dart 2.16.2
import_path_converter 1.0.1

flutter pub run import_path_converter:main
として実行すると、

contains flutter: true
contains registrant: true
┏━━ Converting 221 dart filesUnhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:281:36)
#1      _convertPath (package:import_path_converter/convert.dart:64:51)
#2      convertImports (package:import_path_converter/convert.dart:33:16)
...

といったエラーが出て実行出来なくなりました

**Comment by shachi** [comment]
lib/conver.dart L64
String importPath = line.split(RegExp(r"\'*\'"))[1];

ここで、1個以下の時にエラーが出ているので、

String importPath = (line.split(RegExp(r"\'*\'")).length > 2)
      ? line.split(RegExp(r"\'*\'"))[1]
      : "";

こんな感じに直すのはどうでしょう? (PR出せなかった)

**Comment by shachi** [comment]
あと、import の後に「'」でくくれば問題ないのですが、「"」でくくっているとエラーになりますね……

**Comment by ymgn-dev** [comment]
@shachi 
調査進めていただいてありがとうございます。

申し訳ありませんが、今週が本業でかなり忙しくなってしまったため、修正対応が遅れそうです。
5月末~6月1週目までには時間作って対応できるはずですので、暫くの間お待ちいただければ幸いです。
進捗あり次第報告しますね。
